### ISSUE TITLE
ㅋㅋㅋ...

### ISSUE THREAD

**Issue by kyeongwan** [Sinabro/WrapTalk#2]
https://github.com/Sinabro/WrapTalk/blob/master/WrapTalk/app/src/main/java/com/wraptalk/wraptalk/ChatHeadService.java

소스 분석하고 있는데 현재는 사용안함 뭡니까 ㅠㅠ

**Comment by vbalien** [comment]
ㅋㅋㅋㅋ

**Comment by Sinabro** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ왜 리플이 달리는거지

**Comment by kyeongwan** [comment]
ㅋㅋㅋㅋ 꺅 방문자다
